---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-optparse=1.7.5
  - conda-forge::r-data.table=1.17.8
  - bioconda::bioconductor-rsamtools=2.22.0
