channels:
  - conda-forge
  - bioconda
dependencies:
  - conda=forge::r-poolfstat=3.0.0
  - conda=forge::r-optparse=1.7.5
  - conda=forge::r-tibble=3.2.1
  - conda=forge::r-stringr=1.5.1
  - conda=forge::r-readr=2.1.5
  - conda=forge::r-dplyr=1.1.4
