channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-dplyr=1.1.4
  - conda-forge::r-tidyr=1.3.1
  - conda-forge::r-readr=2.1.5
  - conda-forge::r-purrr=1.0.4
  - conda=forge::r-stringr=1.5.1
  - conda-forge::r-optparse=1.7.5

