channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-dplyr=1.1.4
  - conda-forge::r-tidyr=1.3.1
  - conda-forge::r-readr=2.1.5
  - conda-forge::r-janitor=2.2.1
  - conda-forge::r-purrr=1.0.4
  - conda-forge::r-optparse=1.7.5
  - conda-forge::r-matrixstats=1.5.0
